/* This file is auto-generated by scripts/create-available-templates.js
 * Run "pnpm build:available-templates" to update
 */
const availableTemplates = [
  "http-base",
  "http-react",
  "http-react-hono",
  "cdn-base",
  ""
] as const;
export { availableTemplates };
